export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SELECTED_DELETED_PRODUCT:"SELECTED_DELETED_PRODUCT",
    EDITED_PRODUCT:"EDITED_PRODUCT",
    ADD_PRODUCT:"ADD_PRODUCT",
    BUY_PRODUCT:"BUY_PRODUCT",
}
